Refactor workstation.sh script

diff --git a/src/workstation-setup.sh.erb b/src/workstation-setup.sh.erb
--- a/src/workstation-setup.sh.erb
+++ b/src/workstation-setup.sh.erb
@@ -1,27 +1,76 @@
 #!/bin/sh
 
-# All-in-one workstation zero configuration setup
+set -e
 
-/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+command_exists() {
+	command -v "$@" >/dev/null 2>&1
+}
 
+error() {
+    echo "${RED}""Error: $*""${RESET}" >&2
+}
+
+warn() {
+    echo "${YELLOW}""$*""${RESET}" >&2
+}
+
+announce() {
+    echo "${BLUE}""$*""${RESET}" >&2
+}
+
+success() {
+    echo "${GREEN}""$*""${RESET}" >&2
+}
+setup_color() {
+	# Only use colors if connected to a terminal
+	if [ -t 1 ]; then
+		RED=$(printf '\033[31m')
+		GREEN=$(printf '\033[32m')
+		YELLOW=$(printf '\033[33m')
+		BLUE=$(printf '\033[34m')
+		RESET=$(printf '\033[m')
+	else
+		RED=""
+		GREEN=""
+		YELLOW=""
+		BLUE=""
+		RESET=""
+	fi
+}
+
+setup_color
+
+warn Caching root password...
+sudo -K
+sudo true;
+
+command_exists brew || {
+    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+}
+
+announce Workstation setup...
 brew update
-brew bundle --file=- <<EOT
-<%= view_data.brewfile %>
-EOT
+brew bundle
 
+announce Postgres...
 createuser -s postgres
 
-<% view_data.vsc_extensions.each do |ext| %>
-<%= "/Applications/Visual\\ Studio\\ Code.app/Contents/Resources/app/bin/code --install-extension #{ext}" %>
-<% end %>
+announce Visual Studio Code extensions...
+<% view_data.vsc_extensions.each do |ext| -%>
+/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code --install-extension <%= ext %>
+<% end -%>
 
+announce Hiding the dock...
+defaults write com.apple.dock autohide -bool true
+killall Dock
+
+warn Application that need Security/Accessibility permissions...
 open /Applications/KeepingYouAwake.app
 open /Applications/Divvy.app
 open /Applications/Flycut.app
 open /Applications/Muzzle.app
 
-echo "Adding /usr/local/bin/zsh to /etc/shells"
-grep -q /usr/local/bin/zsh /etc/shells || sudo sh -c "echo /usr/local/bin/zsh >> /etc/shells"
-
 RUNZSH=no sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
 sed -i '' 's/plugins=.*/plugins=(brew git rbenv gem rake bundler node npm heroku postgres redis-cli)/' ~/.zshrc
+
+success All done.
